apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server-ingress
  annotations:
    haproxy.org/ssl-redirect: "true" #https://www.haproxy.com/documentation/kubernetes/latest/configuration/ingress/
spec:
  rules:
  - host: "argocd-{{ .Values.number }}.learn.entigo.io"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: argocd-server
            port:
              name: https 
