kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: test
networking:
  podSubnet: "10.241.0.0/16"
  serviceSubnet: "10.92.0.0/16"
  ipFamily: ipv4
nodes:
- role: control-plane
  image: kreg.learn.entigo.io/hub/kindest/node:v1.21.1
- role: control-plane
  image: kreg.learn.entigo.io/hub/kindest/node:v1.21.1
- role: control-plane
  image: kreg.learn.entigo.io/hub/kindest/node:v1.21.1
- role: worker
  image: kreg.learn.entigo.io/hub/kindest/node:v1.21.1
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress=true"
        register-with-taints: "ingress=true:NoSchedule"
- role: worker
  image: kreg.learn.entigo.io/hub/kindest/node:v1.21.1
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress=true"
        register-with-taints: "ingress=true:NoSchedule"
- role: worker
  image: kreg.learn.entigo.io/hub/kindest/node:v1.21.1
- role: worker
  image: kreg.learn.entigo.io/hub/kindest/node:v1.21.1
- role: worker
  image: kreg.learn.entigo.io/hub/kindest/node:v1.21.1
