
registry: ""
httpport: "80"
httpsport: "443"
monitoringport: "1024"
isdefault: true


nodeSelector:
  ingress: "true"

tolerations:
- key: "ingress"
  operator: "Equal"
  value: "true"
  effect: "NoSchedule"
