apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-applications
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      parameters:
      - name: runenv
        value: {{ .Values.runenv | quote }}
      - name: number
        value: {{ .Values.number | quote }}
    path: argocd-applications
    repoURL: https://github.com/martivo/kind-lab.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

