apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd-yaml/metallb
    repoURL: https://github.com/martivo/kind-lab.git
    targetRevision: HEAD
    helm:
      parameters:
      - name: number
        value: {{ .Values.number }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
